language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - sudo apt-get install libgd2-xpm-dev
install:
  - cpanm --verbose --installdeps --notest .
script:
  - "prove -lr t"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
